"""empty message

Revision ID: 2c125b4b69a5
Revises: 7ada716db359
Create Date: 2024-03-31 12:12:05.854294

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c125b4b69a5'
down_revision: Union[str, None] = '7ada716db359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('date', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
